//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseProject.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        [Required]
        public System.Guid UserId { get; set; }

        [Required]
        public byte UserType { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "First Name: ")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Last Name: ")]
        public string LastName { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Password: ")]
        public string Password { get; set; }

        public string PasswordSalt { get; set; }
    }
}
