//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseProject.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contact
    {
        [Required]
        public System.Guid ContactId { get; set; }

        [Required]
        public System.Guid UserId { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        public string StreetName { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Notes { get; set; }
        
        /*
        [Required]
        public System.Guid contactId { get; set; }

         [Required]
        public System.Guid UserId { get; set; }

        [Required]
        [Display(Name = "First Name: ")]
        public string firstName { get; set; }

        [Required]
        [Display(Name = "Last Name: ")]
        public string lastName { get; set; }

        [Display(Name = "Phone Number: ")]
        public string phoneNumber { get; set; }

        [Display(Name = "Street Name: ")]
        public string streetName { get; set; }

        [Display(Name = "City: ")]
        public string city { get; set; }

        [Display(Name = "Province: ")]
        public string province { get; set; }

        [Display(Name = "Postal Code: ")]
        public string postalCode { get; set; }

        [Display(Name = "Country: ")]
        public string contry { get; set; }

        [Display(Name = "Notes: ")]
        public string Notes { get; set; }
          */
    }
}
